# permissions for end users to edit podsmanages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podsmanage-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: code
    app.kubernetes.io/part-of: code
    app.kubernetes.io/managed-by: kustomize
  name: podsmanage-editor-role
rules:
- apiGroups:
  - podsmanager.my.domain
  resources:
  - podsmanages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podsmanager.my.domain
  resources:
  - podsmanages/status
  verbs:
  - get
