apiVersion: podsmanager.my.domain/v1
kind: PodsManage
metadata:
  labels:
    app.kubernetes.io/name: podsmanage
    app.kubernetes.io/instance: podsmanage-sample
    app.kubernetes.io/part-of: code
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: code
  name: pods-manage-nginx
spec:
  # TODO(user): Add fields here
  imageName: nginx
  image: nginx:1.23
