apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  labels:
    pods-manage: pods-manage-nginx
spec:
  selector:
    matchLabels:
      app: deploy-nginx-server
  replicas: 2
  template:
    metadata:
      labels:
        app: deploy-nginx-server
    spec:
      containers:
      - image: nginx
        name: nginx

